services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "3304:3000"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - OUTDIR=${OUTDIR}
    container_name: borientation-system-app-1
    restart: always 