services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3304:3000"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    container_name: borientation-system-app-1
    restart: always